### PR TITLE
HAUKI-639 vulnerable dependencies

### PR DESCRIPTION
**Pull request by mikkojamG**
Fixing vulnerabilities and removing deprecated packages:
- https://github.com/City-of-Helsinki/hauki-admin-ui/security/dependabot
- https://app.snyk.io/org/city-of-helsinki/project/ac650410-0fae-463a-a4d5-e3a675d92805

Replacing CRA + Jest/Enzyme with Vite and Vitest, which solves multiple vulnerabilities.
Removed unused Cypress tests.

[HAUKI-639](https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-639)

[HAUKI-639]: https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr398-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://hauki-pr398-admin-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr398-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr398-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://hauki-pr398-admin-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr398-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://hauki-pr398-admin-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr398-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://hauki-pr398-admin-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr398-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://hauki-pr398-admin-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr398-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://hauki-pr398-admin-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr398-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://hauki-pr398-admin-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr398-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://hauki-pr398-admin-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr398-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://hauki-pr398-admin-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://hauki-pr398-admin-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]
👍

**Pull request merged**
