### PR TITLE
feat: add language support in all missing places

### PR DESCRIPTION
**Pull request by timwessman**
All UI strings should now have language support.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr402-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://hauki-pr402-admin-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://hauki-pr402-admin-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr402-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://hauki-pr402-admin-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr402-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://hauki-pr402-admin-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mikkojamG — COMMENTED** [review]
Good effort 👍 Noticed that the code coverage is a bit low. Could try adding simple "component renders correctly" tests to increase it a little bit. 🤔

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr402-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr402-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://hauki-pr402-admin-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Pull request merged**
