### PR TITLE
HAUKI-603 start using conventional commits

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description

From now on, all new commit messages must adhere to the [conventional commits spec](https://www.conventionalcommits.org/en/v1.0.0/) and their max line length is limited to 72 characters. The rules are enforced with [commitlint](https://commitlint.js.org/#/), which is run after each commit and also as a stage in the GitHub CI pipeline.

Had to upgrade Node version to 18. [Pipeline changes here.](https://dev.azure.com/City-of-Helsinki/hauki/_git/hauki-pipelines/pullrequest/7931)

## Related Issue(s)

**[HAUKI-603](https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-603)**

## Motivation and Context

We plan to increasingly adopt Conventional Commits in our projects.

## How Has This Been Tested?

Manually, and the CI pipeline passes.

[HAUKI-603]: https://helsinkisolutionoffice.atlassian.net/browse/HAUKI-603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr377-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://hauki-pr377-admin-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr377-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://hauki-pr377-admin-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://hauki-pr377-admin-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr377-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by timwessman — APPROVED** [review]
Looks good, and it works!

**Pull request merged**
