### PR TITLE
build: refactor pipelines OH-36

### PR DESCRIPTION
**Pull request by terovirtanen**
refactor pipelines,
[OH-36](https://helsinkisolutionoffice.atlassian.net/browse/OH-36)

[OH-36]: https://helsinkisolutionoffice.atlassian.net/browse/OH-36?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr368-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://hauki-pr368-admin-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr368-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by danipran — APPROVED** [review]
LGTM! :+1:

**Comment by terovirtanen** [comment]
**HAUKI-ADMIN-UI branch is deployed to platta: https://hauki-pr368-admin-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
